version: '3'

services:
  personio-reminders-service:
    build: .
    container_name: personio-reminders-service
    depends_on:
      - db
    ports:
      - 8000:8080
    environment:
      - DB_HOST=db
      - DB_NAME=reminders
      - DB_USER=postgres
      - DB_PASS=postgres

  db:
    image: 'postgres:13.1-alpine'
    container_name: personio-reminders-service-db
    volumes:
      - personio-reminders-service-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=reminders

volumes:
  personio-reminders-service-db:
    external: false
