---
server.http2.enabled: true
app:
  appName: "Reminders Service"

spring:
  main:
    banner-mode: OFF
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://${DB_HOST:localhost}/${DB_NAME:reminders}"
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    hikari:
      minimumIdle: 1
      maximumPoolSize: 5
      connectionTimeout: 15000
      validationTimeout: 1000
  flyway:
    enabled: true
    clean-disabled: true
  jackson:
    property-naming-strategy: SNAKE_CASE

management:
  endpoints.web:
    base-path: /
    path-mapping:
      health: health-check
    exposure:
      include:
        - health
  endpoint:
    health:
      probes:
        enabled: true

logging:
  config: classpath:logback-spring.xml
