name: Build Gradle project
on:
  push:
jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup and execute Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --info
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: personio-reminders-service
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

